services:
  db:
    image: postgres:16
    container_name: ecomm_nestjs_postgre
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
